# Generated by Django 5.0.7 on 2024-07-24 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_groups', to='cars.car')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_groups', to='locations.locality')),
            ],
            options={
                'unique_together': {('cars', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.IntegerField(default=0)),
                ('cars', models.ForeignKey(help_text='Que auto desea vender?', on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='cars.car')),
                ('location', models.ForeignKey(help_text='Ciudad', on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='locations.locality')),
                ('offer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='offer.offergroup')),
            ],
        ),
    ]
