# Generated by Django 5.0.7 on 2024-07-31 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('locations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_groups', to='cars.car')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_groups', to='locations.locality')),
            ],
            options={
                'unique_together': {('cars', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.IntegerField(default=0)),
                ('cars', models.ForeignKey(help_text='Que auto desea vender?', on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='cars.car')),
                ('location', models.ForeignKey(help_text='Ciudad', on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='locations.locality')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to=settings.AUTH_USER_MODEL)),
                ('offer_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='offer.offergroup')),
            ],
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='offer_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offer.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='offer.offer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='payments.payment')),
            ],
        ),
    ]
