# Generated by Django 5.0.7 on 2024-07-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpayment',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='offer.offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerpayment',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='offer_payments', to='payments.payment'),
            preserve_default=False,
        ),
    ]
