# Generated by Django 5.0.7 on 2024-07-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
