# Generated by Django 5.0.7 on 2024-07-27 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offerpayment_offer_offerpayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='image',
            field=models.ImageField(null=True, upload_to='offer_images/'),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offer.offer'),
            preserve_default=False,
        ),
    ]
