# Generated by Django 5.0.7 on 2024-07-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='country_id',
            new_name='country',
        ),
    ]
